#!/bin/bash

set -e

# Set default params
dry=true
debug=false
target="system"

function error {
	echo "$@"
	exit 1
}

# Parse command line arguments
while [[ "$#" -gt 0 ]]; do
	case $1 in
		-v) debug=true ;;
		-y) dry=false ;;
		-t) target="$2"; shift ;;
		*) error "Unknown parameter passed: $1" ;;
	esac
	shift
done

echo "Target: $target; sfecify another target using: -t target"

command_prefix="echo RUN -> "
if [[ "$dry" == false ]]; then
	read -n 1 -p "This is not a dry run! Type y to continue: " confirm
	if [[ "$confirm" != "y" ]]; then
		exit 0
	fi;
	command_prefix=""
else
	echo "This is a dry run; to run the real deal, add command argument: -y"
fi;

if [[ "$debug" == true ]]; then
	echo "Enabling debug"
	set -x
else
	echo "Debug disabled; to enable, add command argument: -v"
fi;

function mountDevice {
	device=$1
	$command_prefix mkdir -p /mnt/$device
	if [[ $(mount | grep /mnt/$device) ]]; then
		echo "$device already mounted"
	else
		$command_prefix mount /dev/$device /mnt/$device
	fi;
}

function umountDevice {
	device=$1
	if [[ $(mount | grep /mnt/$device) ]]; then
		$command_prefix umount /mnt/$device
		$command_prefix rmdir /mnt/$device
	fi;
}

function syncFromTo {
	from_label=$1
	to_label=$2
	opts=$3
	from=$(blkid --label $from_label | sed 's|/dev/||')
	if [ -z "$from" ]; then
		error "Device with label $from_label was not found"
	fi;
	to=$(blkid --label $to_label | sed 's|/dev/||')
	if [ -z "$to" ]; then
		error "Device with label $to_label was not found"
	fi;

	umountDevice $from
	umountDevice $to
	mountDevice $from
	mountDevice $to
	# TODO: maybe mount source device as read only

	echo "start sync $from to $to"
	if [[ $opts == "delete" ]]; then
		$command_prefix rsync -axHAWXS --numeric-ids --info=progress2 \
		--delete --delete-excluded --exclude='/.gvfs/' --exclude="/mnt/" \
		/mnt/$from/ /mnt/$to/
	else
		$command_prefix rsync -axHAWXS --numeric-ids --info=progress2 \
		--delete-excluded --exclude='/.gvfs/' --exclude="/mnt/" \
		/mnt/$from/ /mnt/$to/
	fi;
	echo "done sync $from to $to"

	umountDevice $from
	umountDevice $to
}

case "$target" in
	"system")
		syncFromTo root bkp_root delete
		syncFromTo home bkp_home delete
		;;
	"storage")
		syncFromTo storage bkp_storage delete
		;;
	"backup")
		syncFromTo backup bkp_backup delete
		;;
	*) error "Unknown target: $target" ;;
esac