#!/bin/bash

while true; do
	echo "1 = webcam"
	echo "2 = droid"
	echo "3 = screen"
	read -n 1 -p "Action : " a
	case $a in
	1)
		ffmpeg -y -loglevel verbose -hwaccel nvdec -crop 120x120x320x320 -c:v mjpeg_cuvid -r:v 30 -i /dev/video0 -an -c:v rawvideo -r:v 30 -vsync cfr -f v4l2 /dev/video10
		;;
	2)
		ffmpeg -i http://192.168.0.100:4747/mjpegfeed?"$@" -vcodec rawvideo -pix_fmt yuv420p -threads 0 -f v4l2 /dev/video10	
		;;
	3)
		ffmpeg -vsync 1 -r:v 30 -f x11grab -s:v 1440x900 -i :0.0 -r:v 30 -f v4l2 /dev/video10
		;;
	*)
		echo "Unknown option"
		;;
	esac
done;
