#!/bin/bash

while true; do
	echo "1 = webcam"
	echo "2 = droid"
	echo "3 = screen"
	read -n 1 -p "Action : " a
	case $a in
	1)
		ffmpeg -vsync 1 -loglevel verbose -hwaccel cuvid -hwaccel_output_format nv12 -c:v mjpeg_cuvid -crop 120x120x320x320 -i /dev/video0 -c:v rawvideo -f v4l2 /dev/video10
		;;
	2)
		ffmpeg -loglevel verbose -i http://192.168.0.100:4747/mjpegfeed -an -c:v copy -f v4l2 /dev/video10
		;;
	3)
		ffmpeg -vsync 1 -r:v 30 -f x11grab -s:v 1440x900 -i :0.0 -r:v 30 -f v4l2 /dev/video10
		;;
	*)
		echo "Unknown option"
		;;
	esac
done;
